export const AGOO_BARANGAYS = [
  "Ambitacay",
  "Balawarte",
  "Capas",
  "Consolacion",
  "Corro-oy",
  "Cuenca",
  "Macalva Central",
  "Macalva Norte",
  "Macalva Sur",
  "Macotoc",
  "Nazareno",
  "Purok",
  "San Agustin East",
  "San Agustin Norte",
  "San Agustin Sur",
  "San Antonino",
  "San Antonio",
  "San Francisco",
  "San Isidro",
  "San Joaquin Norte",
  "San Joaquin Sur",
  "San Jose Norte",
  "San Jose Sur",
  "San Juan",
  "San Julian Central",
  "San Julian East",
  "San Julian Norte",
  "San Julian West",
  "San Manuel Norte",
  "San Manuel Sur",
  "San Marcos",
  "San Miguel",
  "San Nicolas Central",
  "San Nicolas East",
  "San Nicolas Norte",
  "San Nicolas Sur",
  "San Nicolas West",
  "San Pedro",
  "San Roque West",
  "San Vicente Norte",
  "San Vicente Sur",
  "Santa Ana",
  "Santa Barbara",
  "Santa Maria",
  "Santa Monica",
  "Santa Rita",
  "Santa Rita East",
  "Santa Rita Norte",
  "Santa Rita Sur",
  "Santa Rita West"
];
