import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from 'sonner';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased print:h-auto`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col print:h-auto print:min-h-0 print:block" suppressHydrationWarning>
        {children}
        <Toaster 
          position="top-right" 
          duration={4000}
          toastOptions={{
            style: {
              background: 'white',
              color: '#0f172a',
              borderColor: '#e2e8f0'
            },
            classNames: {
              success: 'text-[#006b2c]',
              error: 'text-red-600'
            }
          }}
        />
      </body>
    </html>
  );
}
